Отчет по Теме №11 выполнила:
- Лубянских Елизавета Дмитриевна
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверили:
- к.э.н., доцент Панов М.А.

 ## Лабораторная работа №1
### Простой итератор, но у него нет гибкой настройки, например его нельзя развернуть. Он работает просто как next(), но нет prev()

```python
numbers = [0, 1, 2, 3, 4, 5]
for item in numbers:
    print(item)
```

### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/33346d06-4bd2-4b14-bd97-3a4bb6136d23)

 ## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.
Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.


```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Пётр', 138, 15, 48, 2)
```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/25cb0fc1-96a7-41c1-b123-0607d43dc3d0)



 ## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. 
### Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт.
Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.


```python
def data(*args):
    try:
        for i in range(len(args[0])):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/c5c75746-f477-4f19-90af-27bc5ff0ff4b)

 ## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”
```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```

### Результат.
![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/e3be8bf2-fe82-4bdd-b3c4-6e0b3d73c080)


## Лабораторная работа №5
###  После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции:		init		() (вызывается при создании класса декоратора в программе) и	call	() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('Проверка перед запусклм', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')

@SiteChecker
def site():
    print('Успешная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/eb61e77c-1e1d-4fab-9c67-f854c89ee264)


## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
```python
def fibonacci(): fib1 = fib2 = 1

for i in range(2, 200):
fib1, fib2 = fib2, fib1 + fib2 print(fib2, end=' ')

if		name	== '	main	': 
fibonacci()
```
### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.

```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"\nВремя выполнения функции {func.__name__}: {execution_time} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат
![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/6a318d64-b0c2-4794-b9f4-7206a034343c)


## Выводы.
### Создан декоратор timing_decorator, который измеряет время выполнения функции и выводит его. Затем этот декоратор применяется к функции fibonacci. Когда программа запускается, она выведет числа Фибоначчи и время выполнения функции в консоль.

 ## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такойпроблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(sm2):
    try:
        with open(sm2, 'r') as file:
            read_file = file.read()
            if not read_file:
                raise Exception("Файл пустой")
            else:
                print("Содержимое файла:")
                print(read_file)
    except FileNotFoundError:
        print(f"Файл {sm2} не найден")
    except Exception as e:
        print(f"Ошибка: {e}")

read_file('sm2.txt')
```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/3baa04b3-c123-474d-a9fc-4aae957e560f)


## Выводы.
### В этом примере используется блок try-except для обработки исключений. Если файл не найден, программа выводит сообщение об этом. Если файл пустой, программа вызывает исключение с сообщением "Файл пустой". Если файл содержит информацию, она выводится в консоль.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
# -*- coding: windows-1251 -*-
def add_two_numbers():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)
        result = 2 + number
        print(f"Результат сложения 2 и {number}: {result}")
    except ValueError:
        print("Ошибка: Неподходящий тип данных. Ожидалось число.")

# Тест 1: ввод корректного числа
add_two_numbers()

# Тест 2: ввод строки
add_two_numbers()

# Тест 3: ввод другого неподходящего типа данных
add_two_numbers()
```
### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/37da9999-0bdb-4ebe-86d1-af804ebd2ad1)


## Выводы. 
### В данной программе функция add_two_numbers считывает число, пробует преобразовать его в тип float и затем складывает с числом 2. Если пользователь вводит неподходящий тип данных, например, строку, программа перехватывает исключение ValueError и выводит соответствующее сообщение об ошибке.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
import time

# Создаем класс декоратора
class CallInfoDecorator:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        # Запоминаем текущее время
        start_time = time.time()

        # Вызываем функцию и сохраняем ее результат
        result = self.func(*args, **kwargs)

        # Вычисляем время выполнения функции
        execution_time = time.time() - start_time

        # Выводим информацию о вызове функции
        print(f"Функция {self.func.__name__} была вызвана с аргументами {args} и ключевыми аргументами {kwargs}")
        print(f"Время выполнения функции: {execution_time} секунд\n")

        # Возвращаем результат функции
        return result

# Определяем две функции, к которым будем применять декоратор
@CallInfoDecorator
def multiply(x, y):
    return x * y

@CallInfoDecorator
def greet(name):
    return f"Привет, {name}!"

# Тестируем работу декоратора
result = multiply(5, 7)
print(result)  # Выведет: 35

result = greet("Вася")
print(result)  # Выведет: Привет, Вася!
```
## Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/8194a77c-17d2-4276-925c-dd4e5ea78b80)

## Выводы.
### Таким образом, декоратор CallInfoDecorator успешно применяется к функциям multiply и greet, и выводит информацию о вызове и времени выполнения каждой функции.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomException(Exception):
    def __init__(self, message):
        super().__init__(message)
        self.message = message


def example_function(number):
    if number < 0:
        raise CustomException("Неверный ввод. Число должно быть положительным.")
    else:
        return number ** 2


try:
    input_number = int(input("Введите положительное число: "))
    result = example_function(input_number)
    print("Результат:", result)
except CustomException as e:
    print("Ошибка:", e.message)
```
### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/42a77012-22ea-4613-889d-ad52b8c050d2)

## Выводы. 
### В данном примере определен класс CustomException, который является наследником класса Exception. В конструкторе класса CustomException определена инициализация сообщения об ошибке. 

Затем определена функция example_function, которая получает на вход число и проверяет его значение. Если значение меньше нуля, то вызывается исключение CustomException с сообщением "Ошибка: Неверный ввод. Число должно быть положительным.". Иначе, функция возвращает квадрат введенного числа.

В основной части кода происходит запрос на ввод поло
